name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  checks: write

jobs:
  integration:
    uses: nikolhodos/integration-workflow/.github/workflows/python-integration.yml@main

  build:
    runs-on: ubuntu-latest
    needs: [integration]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/real-madrid-results:latest
          push: true

  create-artifact:
    needs: [build]
    uses: nikolhodos/integration-workflow/.github/workflows/create-artifact.yml@main

  results:
    runs-on: ubuntu-latest
    needs: [create-artifact]
    env:
      API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python app/main.py

  development:
    environment: Development
    needs: [results]
    runs-on: ubuntu-latest
    steps:
      - run: echo "- Auto-deploy the artifact to the development environment"

  staging:
    environment: Staging
    needs: [development]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "After development environment is deployed..."
          echo "- Auto-deploy the artifact to the staging environment"

  test-staging:
    needs: staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "- Test the staging environment"

  production:
    environment: Production
    needs: [test-staging]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "After staging environment is deployed..."
          echo "and after the staging tests have passed..."
          echo "- Deploy the artifact to the production environment"

  test-production:
    needs: [production]
    runs-on: ubuntu-latest
    steps:
      - run: echo "- Test the artifact in the production environment"
      - run: echo "# Everything completed successfully!" >> $GITHUB_STEP_SUMMARY